In [2]:
import numpy as np

In [16]:
lst1 = [[1], [2], [3]]
lst2 = [[6], [5], [4]]
a = np.array(lst1)
b = np.array(lst2)
c = np.concatenate((a, b), axis = 1)
c

array([[1, 6],
       [2, 5],
       [3, 4]])

In [34]:
l1 = [[1], [2], [3], [4]]
a1 = np.array(l1)
l2 = [[5], [6], [7], [8]]
a2 = np.array(l2)
l3 = [[9], [10], [11], [12]]
a3 = np.array(l3)
cc1 = [l1, l2, l3]
aa1 = np.array(cc1)
aa2 = np.concatenate((a1, a2, a3[::-1]), axis = 0)
print(aa1.ndim)
aa2

3


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [12],
       [11],
       [10],
       [ 9]])

In [35]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [76]:
re1 = np.arange(6)
print(re1)
re2 = re1.reshape(3, 1, 1, -1)
print(re2)

[0 1 2 3 4 5]
[[[[0 1]]]


 [[[2 3]]]


 [[[4 5]]]]


In [66]:
a = np.array([[1], [2], [3], [4], [5], [6]])
a2 = a[: , :, np.newaxis]
a3 = a[: , np.newaxis, np.newaxis]
a4 = a[np.newaxis, :, :]
print(a)
print(a2)
print(a3)
print(a4)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]]
[[[[1]]]


 [[[2]]]


 [[[3]]]


 [[[4]]]


 [[[5]]]


 [[[6]]]]
[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]]]
[1 2 3 4 5 6]


In [71]:
a = np.array([1, 2, 3, 4, 5, 6])
a2 = a[np.newaxis, :]
a3 = a[ : , np.newaxis]
print(a)
print(a2)
print(a3)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [84]:
b = np.expand_dims(a3, axis=(2))
print(b)

[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]]


In [97]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 12])
five_up = (a >= 5)
print(five_up)
print(a[five_up])
print(a[
        np.array([[False, False, False, False],
                  [ True,  True,  True,  True],
                  [ True,  True,  True,  True]])
       ])

[ 1  2  3  4  5  6  7  8  9 10 11]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [99]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 6)
print(b)

(array([0, 0, 0, 0, 1]), array([0, 1, 2, 3, 0]))


In [108]:
for ind1, ind2 in zip(b[0], b[1]):
    print((ind1, ind2))
for ind1, ind2 in zip(b[0], b[1]):
    print(ind1, ind2)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))
(np.int64(1), np.int64(0))
0 0
0 1
0 2
0 3
1 0


In [109]:
not_there = np.nonzero(a == 42)
a[not_there]

array([], dtype=int64)

In [104]:
names = ['Alice', 'Bob', 'Charlie']
ages = [25, 30, 35]

# 使用 zip() 并行迭代两个列表
for name, age in zip(names, ages):
    print(f"{name} is {age} years old.")

Alice is 25 years old.
Bob is 30 years old.
Charlie is 35 years old.


In [130]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])
t1 = np.concatenate((a1, a2), axis = 0)
t2 = np.concatenate((a1, a2), axis = 1)
print(t1)
print(t2)
stack1 = np.vstack((a1, a2))
print(stack1)
stack2 = x = np.arange(1, 25).reshape(2, 12)
print(stack2)
t1[ 0:2 , 0:1]

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


array([[1],
       [2]])

In [128]:
a1 = np.array([[[1], [1]],
               [[2], [2]]])
a2 = np.array([[[3], [3]],
               [[4], [4]]])
st1 = np.vstack((a1, a2))
st2 = np.hstack((a1, a2))
print(a1)
print(a2)
print(st1)
print(st2)

[[[1]
  [1]]

 [[2]
  [2]]]
[[[3]
  [3]]

 [[4]
  [4]]]
[[[1]
  [1]]

 [[2]
  [2]]

 [[3]
  [3]]

 [[4]
  [4]]]
[[[1]
  [1]
  [3]
  [3]]

 [[2]
  [2]
  [4]
  [4]]]


In [143]:
x = np.arange(1, 25).reshape(3, 2, 4)
print(x)
np.hsplit(x, (0, 1))
#不理解

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


[array([], shape=(3, 0, 4), dtype=int64),
 array([[[ 1,  2,  3,  4]],
 
        [[ 9, 10, 11, 12]],
 
        [[17, 18, 19, 20]]]),
 array([[[ 5,  6,  7,  8]],
 
        [[13, 14, 15, 16]],
 
        [[21, 22, 23, 24]]])]